add working favourite Button
matwjablonski/kodilla-wdp2411-01 pull request #11
Opened 2024-11-20 14:08 UTC by kalipp1

I added functionality to favorite button now we can change favorite state

2024-11-20 14:29 UTC, matwjablonski requested changes

2024-11-20 14:29 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +    if (event.preventDefault) {
why you need that check?

2024-11-20 14:29 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    color: black;
colors only from variables, and don't use named colors

2024-11-20 14:44 UTC, kalipp1 commented on src/components/common/ProductBox/ProductBox.js
> +    if (event.preventDefault) {
All changes here done :D

2024-11-21 12:57 UTC, NocnyZwierz submitted a review, later dismissed
Greate job!

2024-11-21 20:51 UTC, NocnyZwierz approved these changes
Good work!

2024-11-25 16:34 UTC, NocnyZwierz submitted a review, later dismissed

2024-11-27 20:18 UTC, NocnyZwierz submitted a review, later dismissed

2024-11-28 09:58 UTC, NocnyZwierz approved these changes

2024-11-28 15:13 UTC, matwjablonski approved these changes

2024-11-28 15:13 UTC, merged