add RWD styles for feature Boxes
matwjablonski/kodilla-wdp2411-01 pull request #15
Opened 2024-11-22 00:58 UTC by kalipp1

What you think about this?

2024-11-23 15:29 UTC, NocnyZwierz submitted a review, later dismissed

2024-11-25 20:58 UTC, NocnyZwierz submitted a review, later dismissed
It looks great. Keep up the good work!

2024-11-26 16:56 UTC, matwjablonski requested changes

2024-11-26 16:56 UTC, matwjablonski commented on src/components/features/FeatureBoxes/FeatureBoxes.module.scss
> +      display: flex !important;
nope, !important to remove, find different way

2024-11-26 21:20 UTC, kalipp1 commented on src/components/features/FeatureBoxes/FeatureBoxes.module.scss
> +      display: flex !important;
I found other and simpler way. What you think about this idea?

2024-11-27 20:16 UTC, NocnyZwierz approved these changes

2024-11-27 21:53 UTC, matwjablonski approved these changes

2024-11-27 21:53 UTC, merged