add Hover for buttons in boxes
matwjablonski/kodilla-wdp2411-01 pull request #5
Opened 2024-11-18 12:41 UTC by kalipp1

I added hover for buttons and price button. What you think about red background in price box ?

2024-11-19 07:09 UTC, NocnyZwierz submitted a review, later dismissed
:)

2024-11-20 14:22 UTC, matwjablonski requested changes

2024-11-20 14:22 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +      background-color: red;
please use variable for the color. colors should be also represented by hex or rgb

2024-11-20 21:16 UTC, NocnyZwierz submitted a review, later dismissed

2024-11-23 12:35 UTC, NocnyZwierz approved these changes
:)

2024-11-23 20:37 UTC, matwjablonski approved these changes

2024-11-23 20:37 UTC, merged