add category list, opening by hover on it
matwjablonski/kodilla-wdp2411-01 pull request #9
Opened 2024-11-19 11:58 UTC by kalipp1

I had a lot of fun working on it. What you think about this idea?

2024-11-19 14:18 UTC, NocnyZwierz commented
It would be good to add between categories border-bottom: solid. The width of the drop-down list must be equal to the button. It's good for the list to appear just below the button. :)

2024-11-20 14:27 UTC, matwjablonski requested changes

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +        li {
please remove so deep nesting, use css classes instead

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +            border-bottom: 1px solid black;
color as hex or rgb 

and from variable

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +          background-color: lightgray;
same, as above

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +        background-color: lightgray;
same, as above

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +            color: black;
same, as above

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      option{
add space before {

2024-11-20 14:27 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    background-color: lightgray;
color

2024-11-21 20:49 UTC, NocnyZwierz approved these changes
Easy peasy lemon squeezy! Nice work!

2024-11-23 15:30 UTC, NocnyZwierz approved these changes

2024-11-25 15:17 UTC, matwjablonski approved these changes

2024-11-25 16:04 UTC, NocnyZwierz submitted a review, later dismissed

2024-11-26 16:52 UTC, matwjablonski submitted a review, later dismissed

2024-11-27 21:51 UTC, matwjablonski approved these changes

2024-11-27 21:51 UTC, merged